controller_manager:
  ros__parameters:
    update_rate: 100  # H
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    mobile_base_controller:
      type: diff_drive_controller/DiffDriveController

mobile_base_controller:
  ros__parameters:
    publish_rate: 50
    base_frame_id: base_link

    # left_wheel: ["drivewhl_l_front_joint", "drivewhl_l_back_joint"]
    # right_wheel: ["drivewhl_r_front_joint", "drivewhl_r_back_joint"]
    left_wheel: ["drivewhl_l_front_joint"]
    right_wheel: ["drivewhl_r_front_joint"]
    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.03]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 1000000.0, 1000000.0, 0.03]
    cmd_vel_timeout: 0.25

    # Odometry fused with IMU is published by robot_localization, so
    # no need to publish a TF based on encoders alone.
    enable_odom_tf: false

    # Wheel separation and radius multipliers
    wheel_separation_multiplier: 1.0 # default: 1.0
    wheel_radius_multiplier    : 1.0 # default: 1.0

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear:
      x:
        has_velocity_limits    : true
        max_velocity           : 2.0   # m/s
        has_acceleration_limits: true
        max_acceleration       : 20.0   # m/s^2
    angular:
      z:
        has_velocity_limits    : true
        max_velocity           : 4.0   # rad/s
        has_acceleration_limits: true
        max_acceleration       : 25.0   # rad/s^2